commit

diff --git a/.github/workflows/test-tf-plan-apply.yml b/.github/workflows/test-tf-plan-apply.yml
--- a/.github/workflows/test-tf-plan-apply.yml
+++ b/.github/workflows/test-tf-plan-apply.yml
@@ -1,7 +1,7 @@
-name: "zReusable: Terraform Plan/Apply"
+name: Tearrform CAP Deployment
 
 on:
-  workflow_dispatch:
+  workflow_call:
     inputs:
       environment:
         required: true
@@ -22,36 +22,32 @@ on:
         required: false
         type: string
         default: "./tfvars/"
-
-# Outputs moved to workflow level
-outputs:
-  apply_completed:
-    description: boolean value determining whether a Terraform Apply had been completed with changes applied
-    value: ${{ jobs.terraform-apply.outputs.apply_completed }}
+    outputs:
+      apply_completed:
+        description: boolean value determining whether a Terraform Apply had been completed with changes applied
+        value: ${{ jobs.terraform-apply.outputs.apply_completed }}
 
 #Special permissions required for OIDC authentication
 permissions:
-  id-token: write
-  contents: read
-  pull-requests: write
+    id-token: write
+    contents: read
+    pull-requests: write
 
 #These environment variables are used by the terraform azure provider to setup OIDC auth.
 env:
-  # ARM_USE_OIDC: true
-  ARM_USE_AZUREAD: true
-  ARM_ENVIRONMENT: ${{ vars.TF_BACKEND_CONFIG_ENVIRONMENT }}
+    # ARM_USE_OIDC: true
+    ARM_USE_AZUREAD: true
+    ARM_ENVIRONMENT: ${{ vars.TF_BACKEND_CONFIG_ENVIRONMENT }}
+    
+    TF_VAR_ci_environment_name: ${{ inputs.environment }}
+    TF_VAR_maintenance_mode: "${{ inputs.maintenance_mode }}"
   
-  TF_VAR_ci_environment_name: ${{ inputs.environment }}
-  TF_VAR_maintenance_mode: "${{ inputs.maintenance_mode }}"
-
-  ## tfvars file path vars  
-  TFVARS_FOLDER: "${{ inputs.tfvars_folder || './tfvars/' }}"
-  TFVARS_TENANT_FILE: "${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}.tfvars"  
-  TFVARS_COMMON_FILE: "common.tfvars"  
-
-  TF_VAR_management_tenant_tenant_id: ${{ vars.IS_AZURE_GOV == 'true' && vars.MANAGEMENT_TENANT_ID || vars.COMMERCIAL_MANAGEMENT_TENANT_ID}}
-  AWS_REGION: ${{ vars.TFSTATE_REGION }}
-  AWS_ROLE_ARN: ${{ vars.TFSTATE_ROLE_ARN }}
+    ## tfvars file path vars  
+    TFVARS_FOLDER: "${{ inputs.tfvars_folder || './tfvars/' }}"
+    TFVARS_TENANT_FILE: "${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}.tfvars"  
+    TFVARS_COMMON_FILE: "common.tfvars"  
+  
+    TF_VAR_management_tenant_tenant_id: ${{ vars.IS_AZURE_GOV == 'true' && vars.MANAGEMENT_TENANT_ID || vars.COMMERCIAL_MANAGEMENT_TENANT_ID}}
 
 jobs:
   terraform-plan:
@@ -68,11 +64,11 @@ jobs:
       tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
 
     steps:
-      - name: Setup AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ vars.TFSTATE_ROLE_ARN }}
-          aws-region: ${{ vars.TFSTATE_REGION }}
+    #   - name: Setup AWS Credentials
+    #     uses: aws-actions/configure-aws-credentials@v4
+    #     with:
+    #       role-to-assume: 
+    #       aws-region: 
 
       - name: Authenticate and set Graph Access Token
         shell: pwsh
@@ -82,6 +78,7 @@ jobs:
           }
           az login --service-principal -u ${{ vars.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ vars.AZURE_TENANT_ID }}
           $AccessToken = (az account get-access-token --resource-type ms-graph | ConvertFrom-Json).accessToken
+
       # Checkout the repository to the GitHub Actions runner
       - name: Checkout
         uses: actions/checkout@v4
@@ -97,15 +94,27 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}
 
-      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-      - name: Terraform Init
-        working-directory: ${{ inputs.working_dir }}
+      - name: Terraform Apply
+        if: github.ref == 'refs/heads/main'
+        run: terraform apply -auto-approve tfplan
+
+      - name: Cleanup SSH Keys
+        if: always()
+        run: rm -rf ~/.ssh 
+
+      - name: Copy Backend Configuration
         run: |
-          terraform init --backend-config='bucket=${{ vars.TFSTATE_S3_BUCKET }}' \
-                          --backend-config='key=${{ vars.TFSTATE_KEY }}' \
-                          --backend-config='dynamodb_table=${{ vars.TFSTATE_DYNAMODB_TABLE }}' \
-                          --backend-config='encrypt=true'
-      # Checks that all Terraform configuration files adhere to a canonical format
+            BACKEND_FILE="backend/${{ inputs.environment }}.tf"
+            if [ ! -f "$BACKEND_FILE" ]; then
+            echo "Error: Backend configuration file $BACKEND_FILE does not exist"
+            exit 1
+            fi
+            cp "$BACKEND_FILE" .
+
+      - name: Terraform Init
+        run: terraform init
+
+     # Checks that all Terraform configuration files adhere to a canonical format
       # Will fail the build if not
       - name: Terraform Format
         working-directory: ${{ inputs.working_dir }}
@@ -121,14 +130,18 @@ jobs:
         #   TF_LOG : "DEBUG"
         run: |
           export exitcode=0
+
           terraform plan -detailed-exitcode -no-color -out tfplan -var-file="$TFVARS_FOLDER$TFVARS_TENANT_FILE" -var-file="$TFVARS_FOLDER$TFVARS_COMMON_FILE" -lock-timeout=2m || export exitcode=$?
+
           echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
           if [ $exitcode -eq 1 ]; then
             echo Terraform Plan Failed!
             exit 1
           else
             exit 0
           fi
+
       # Save plan to artifacts
       - name: Publish Terraform Plan
         uses: actions/upload-artifact@v4
@@ -142,6 +155,7 @@ jobs:
         working-directory: ${{ inputs.working_dir }}
         run: |
           TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+
           delimiter="$(openssl rand -hex 8)"
           echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
           echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
@@ -152,6 +166,7 @@ jobs:
           echo '```' >> $GITHUB_OUTPUT
           echo "</details>" >> $GITHUB_OUTPUT
           echo "${delimiter}" >> $GITHUB_OUTPUT
+
       # Publish Terraform Plan as task summary
       - name: Publish Terraform Plan to Task Summary
         working-directory: ${{ inputs.working_dir }}
@@ -159,6 +174,7 @@ jobs:
           SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
         run: |
           echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+
       # If this is a PR post the changes
       - name: Push Terraform Output to PR
         if: github.event.pull_request != null
@@ -175,13 +191,7 @@ jobs:
                 repo: context.repo.repo,
                 body: body
             })
-  ## Conditions for Terraform Apply to run:
-  ## 1. Terraform plan produces exit code 2 (changes to apply)
-  ## AND
-  ## 2. The event is a workflow_dispatch, execute_change is true, and the actor is in the ALLOWED_MANUAL_DEPLOYERS list OR the event is a push to main
-  ## This is to allow manual deployments to be triggered from the GitHub UI, specifically for testing changes during Pull Requests, prior to merging.
-  ## The ALLOWED_MANUAL_DEPLOYERS list is a comma-separated list of GitHub usernames
-  ## e.g. ALLOWED_MANUAL_DEPLOYERS: "user1,user2,user3"
+
   terraform-apply:
     env:
       ARM_RESOURCE_PROVIDER_REGISTRATIONS : none
@@ -225,14 +235,18 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}
 
-      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-      - name: Terraform Init
-        working-directory: ${{ inputs.working_dir }}
+      - name: Copy Backend Configuration
         run: |
-          terraform init  --backend-config='bucket=${{ vars.TFSTATE_S3_BUCKET }}' \
-                          --backend-config='key=${{ vars.TFSTATE_KEY }}' \
-                          --backend-config='dynamodb_table=${{ vars.TFSTATE_DYNAMODB_TABLE }}' \
-                          --backend-config='encrypt=true'
+            BACKEND_FILE="backend/${{ inputs.environment }}.tf"
+            if [ ! -f "$BACKEND_FILE" ]; then
+            echo "Error: Backend configuration file $BACKEND_FILE does not exist"
+            exit 1
+            fi
+            cp "$BACKEND_FILE" .
+
+      - name: Terraform Init
+        run: terraform init
+
       # Download saved plan from artifacts
       - name: Download Terraform Plan
         uses: actions/download-artifact@v4
@@ -249,6 +263,7 @@ jobs:
             -auto-approve `
             --target module.azure-policies-log.azurerm_subscription_policy_assignment.policy_asgn `
             --target module.azure-policies-sec.azurerm_subscription_policy_assignment.policy_asgn
+
       # Terraform Apply
       - name: Terraform Apply
         id: terraform_apply
@@ -259,6 +274,7 @@ jobs:
         run: |
           terraform apply -auto-approve -var-file="$TFVARS_FOLDER$TFVARS_TENANT_FILE" -var-file="$TFVARS_FOLDER$TFVARS_COMMON_FILE" tfplan
           echo "apply_completed=true" >> $GITHUB_OUTPUT
+
           
       - name: Disable Maintenance Mode
         if: ${{ inputs.maintenance_mode == true }}
@@ -267,6 +283,7 @@ jobs:
           TF_VAR_maintenance_mode: 'false'
         run: |
           Write-Output "Disabling Maintenance Mode"
+
           terraform apply `
             -auto-approve `
             --target module.azure-policies-log.azurerm_subscription_policy_assignment.policy_asgn `
